### ISSUE TITLE
Can't find file

### ISSUE THREAD

**Issue by brandonhilkert** [josemarluedke/ember-cli-daterangepicker#4]
I'm getting an error when trying to use the addon:

```
Error: Path or pattern "bower_components/bootstrap-daterangepicker/daterangepicker.js" did not match any files
    at Object.multiGlob (/Users/bhilkert/Dropbox/code/pipeline-backend/node_modules/ember-cli/node_modules/broccoli-kitchen-sink-helpers/index.js:202:13)
    at Class.module.exports.CachingWriter.extend.addFiles (/Users/bhilkert/Dropbox/code/pipeline-backend/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:74:13)
    at Class.module.exports.CachingWriter.extend.updateCache (/Users/bhilkert/Dropbox/code/pipeline-backend/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:52:12)
    at /Users/bhilkert/Dropbox/code/pipeline-backend/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/index.js:92:34
    at lib$rsvp$$internal$$tryCatch (/Users/bhilkert/Dropbox/code/pipeline-backend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/bhilkert/Dropbox/code/pipeline-backend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/Users/bhilkert/Dropbox/code/pipeline-backend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)
    at lib$rsvp$asap$$flush (/Users/bhilkert/Dropbox/code/pipeline-backend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1290:9)
    at process._tickCallback (node.js:355:11)
```

I couldn't find any references to that path in the addon. Any idea?

**Comment by brandonhilkert** [comment]
My bad. Didn't read the dependencies close enough.
